### ISSUE TITLE
vorbis-tools 1.4.3 fails to compile with gcc 15.2

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#116]
I was able to build vorbis-tools 1.4.3 with gcc 13.2, but it fails with gcc 15.2.

```
../../src/share/getopt.c:399:21: error: too many arguments to function 'getenv'; expected 0, have 1
  399 |   posixly_correct = getenv ("POSIXLY_CORRECT");
      |                     ^~~~~~  ~~~~~~~~~~~~~~~~~
../../src/share/getopt.c:207:14: note: declared here
  207 | extern char *getenv ();
      |              ^~~~~~
```

```
../../src/share/getopt.c: In function 'getopt':
../../src/share/getopt.c:964:1: warning: old-style function definition [-Wold-style-definition]
  964 | getopt (argc, argv, optstring)
      | ^~~~~~
../../src/share/getopt.c:968:1: error: number of arguments doesn't match prototype
  968 | {
      | ^
In file included from ../../src/share/getopt.c:104:
../../src/include/getopt.h:136:12: error: prototype declaration
  136 | extern int getopt ();
      |            ^~~~~~
```

```
../../src/ogginfo/ogginfo2.c: In function 'main':
../../src/ogginfo/ogginfo2.c:430:19: error: too many arguments to function 'getopt'; expected 0, have 3
  430 |     while ((ret = getopt(argc, argv, "hqvV")) >= 0) {
      |                   ^~~~~~ ~~~~
In file included from ../../src/ogginfo/ogginfo2.c:20:
../../src/include/getopt.h:136:12: note: declared here
  136 | extern int getopt ();
      |            ^~~~~~
```
